name: Xlog

# This workflow will build the site and deploy it to GitHub Pages.
# It is triggered on push to the master branch and can also be run manually.
# The workflow uses the xlog tool to build the site and deploys it using GitHub Actions.
# The workflow is set to run on the latest version of Ubuntu.
# The workflow uses the actions/checkout action to check out the code.
# The workflow uses the chetan/git-restore-mtime-action action to restore the timestamps of the files.
# The workflow uses the actions/upload-pages-artifact action to upload the built site as an artifact.
# The workflow uses the actions/deploy-pages action to deploy the site to GitHub Pages.
# The workflow uses the actions/github-script action to run a script that sets the permissions for the pages.
#
# The page will be published as 
# 
#    https://ofenloch.github.io/oliver.ofenloch.github.io/
#
#

on:

  push:

    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:


permissions:

  contents: read

  pages: write

  id-token: write


concurrency:

  group: "pages"

  cancel-in-progress: true


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4

        with:

          fetch-depth: 0


      - name: Allow non-ASCII character

        run: git config core.quotepath false


      - name: restore timestamps

        uses: chetan/git-restore-mtime-action@v1


      - name: Install xlog

        env:

          XLOG_VERSION: v1.7.8

        run: curl --location https://github.com/emad-elsaid/xlog/releases/download/${XLOG_VERSION}/xlog-${XLOG_VERSION}-linux-amd64.tar.gz | tar -xz -C ..


      - name: Build

        run: |
          cp -pvf README.md index.md

          ../xlog --build . --sitename "@ofenloch" --github.url https://github.com/ofenloch/oliver.ofenloch.github.io/edit/master

          rm *.md

          chmod -R 0777 .          


      - name: Upload GitHub Pages artifact

        uses: actions/upload-pages-artifact@v3.0.1

        with:

          path: .


  deploy:

    environment:

      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Deploy to GitHub Pages

        id: deployment

        uses: actions/deploy-pages@v4
